# -*- coding: utf-8 -*-
"""EHR_modelDevelopment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTSyV_r9XGdg9ykyxYwyp9UXEbQK2ZdU

# Model Development (Traditional ML)
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -U scikit-learn==1.3.2 pandas numpy scipy
!pip install -U xgboost lightgbm catboost



"""# Model dev_1"""

# XGBoost, Logistic Regression (LR), Support Vector Machine (SVM: SVC & SVR),
# Decision Tree, Random Forest, LightGBM, and CatBoost
# Ethnic difference consideration

# ============================================================
# Traditional ML Models + Ethnicity Subgroup Analysis
# Tasks:
#   (1) Predict hospital_expire_flag (classification)
#   (2) Predict length of stay los_days (regression)
# Models:
#   Logistic Regression, SVM, Decision Tree, XGBoost, LightGBM, CatBoost
# Outputs:
#   Metrics + CIs + plots saved in:
#     plots/classification/
#     plots/regression/
# ============================================================

# ----------------------------
# 0) Silence warnings (cleaner logs)
# ----------------------------
import warnings  # import warnings module
warnings.filterwarnings("ignore")  # ignore warning messages (optional)

# ----------------------------
# 1) Core libraries
# ----------------------------
import numpy as np  # numerical arrays and math operations
import pandas as pd  # dataframe handling
import ast  # safely parse stringified lists like "['A','B']"
from typing import List, Dict, Tuple, Any

# ----------------------------
# 2) Plotting libraries
# ----------------------------
import matplotlib.pyplot as plt  # base plotting
import seaborn as sns  # nicer statistical plots

# ----------------------------
# 3) Sparse matrix support
# ----------------------------
from scipy import sparse  # sparse matrix operations (CSR matrix)


# ----------------------------
# 5) Scikit-learn utilities
# ----------------------------
from sklearn.model_selection import GroupShuffleSplit, GroupKFold, learning_curve  # grouped splitting & learning curves
from sklearn.preprocessing import StandardScaler, MultiLabelBinarizer  # scaling and multi-hot encoding
from sklearn.pipeline import Pipeline  # pipelines to chain preprocessing + model
from sklearn.impute import SimpleImputer  # missing value imputation
from sklearn.metrics import (  # evaluation metrics
    roc_auc_score, roc_curve,  # ROC-AUC + ROC curve
    precision_recall_fscore_support,  # precision/recall/F1
    classification_report,     # full text classification report
    average_precision_score,   # AUPRC
    confusion_matrix, ConfusionMatrixDisplay, precision_recall_curve  # confusion matrix + display
)
from sklearn.linear_model import LogisticRegression  # Logistic Regression classifier
from sklearn.svm import SVC, SVR  # Support Vector classification/regression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor  # Decision Tree models
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor  # Random Forest models
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score  # regression metrics

# ----------------------------
# 6) Boosting models
# ----------------------------
from xgboost import XGBClassifier, XGBRegressor  # XGBoost models
import lightgbm as lgb  # LightGBM interface
from catboost import CatBoostClassifier, CatBoostRegressor  # CatBoost models

# ----------------------------
# 7) Plot saving utilities (folders + safe naming)
# ----------------------------
from pathlib import Path  # filesystem paths
import re  # regex for filename cleanup

PLOTS_ROOT = Path("/content/drive/MyDrive/EHR/plots")  # root folder for plots
CLS_DIR = PLOTS_ROOT / "classification"  # folder for classification plots
REG_DIR = PLOTS_ROOT / "regression"  # folder for regression plots

CLS_DIR.mkdir(parents=True, exist_ok=True)  # create classification folder if not exists
REG_DIR.mkdir(parents=True, exist_ok=True)  # create regression folder if not exists


SHOW_PLOTS = True  # if True: show and save; if False: save only

def _safe_name(s: str) -> str:
    """
    Convert any text into a safe filename fragment.
    """
    s = str(s).strip().lower()  # lowercase and trim whitespace
    s = re.sub(r"[^a-z0-9\-_]+", "_", s)  # replace unsafe chars with underscore
    return s.strip("_")  # remove leading/trailing underscores

def save_current_fig(filename: str, out_dir: Path, dpi: int = 200) -> Path:
    """
    Save the currently active matplotlib figure to disk and close it.
    """
    out_dir.mkdir(parents=True, exist_ok=True)  # ensure folder exists
    path = out_dir / filename  # full output path
    plt.tight_layout()  # compact layout to avoid clipped labels
    plt.savefig(path, dpi=dpi, bbox_inches="tight")  # save figure
    if SHOW_PLOTS:  # optionally show
        plt.show()
    plt.close()  # close to avoid memory buildup
    return path  # return saved path

# ============================================================
# Helper Functions
# ============================================================

def parse_list_cell(x) -> List[str]:
    """
    Parse list-like strings in the CCSR column into a Python list.
    Example input: "['CIR009','DIG016']" -> ['CIR009', 'DIG016']
    """
    if x is None:  # if missing
        return []
    if isinstance(x, float) and np.isnan(x):  # if NaN
        return []
    if isinstance(x, list):  # already a list
        return x
    s = str(x).strip()  # convert to string
    if s == "" or s == "[]":  # empty list cases
        return []
    try:
        v = ast.literal_eval(s)  # safely parse to Python object
        return v if isinstance(v, list) else []  # return list if valid
    except Exception:
        return []  # fallback if parsing fails

def bootstrap_ci_classification(
    y_true: np.ndarray,
    y_prob: np.ndarray,
    y_pred: np.ndarray,
    n_boot: int = 2000,
    seed: int = 42
) -> Dict[str, Tuple[float, float]]:
    """
    Stratified bootstrap confidence intervals for AUROC and F1.
    Uses stratified sampling to keep class balance in resamples.
    """
    rng = np.random.default_rng(seed)  # reproducible RNG
    y_true = np.asarray(y_true)  # ensure array
    y_prob = np.asarray(y_prob)  # ensure array
    y_pred = np.asarray(y_pred)  # ensure array

    idx_pos = np.where(y_true == 1)[0]  # indices of positives
    idx_neg = np.where(y_true == 0)[0]  # indices of negatives

    if len(idx_pos) == 0 or len(idx_neg) == 0:  # need both classes
        return {"AUROC_CI": (np.nan, np.nan), "F1_CI": (np.nan, np.nan)}

    aucs = []  # store bootstrap AUROCs
    f1s = []  # store bootstrap F1s

    for _ in range(n_boot):  # bootstrap iterations
        samp_pos = rng.choice(idx_pos, size=len(idx_pos), replace=True)  # resample positives
        samp_neg = rng.choice(idx_neg, size=len(idx_neg), replace=True)  # resample negatives
        samp = np.concatenate([samp_pos, samp_neg])  # combine indices

        yt = y_true[samp]  # bootstrap true labels
        yp = y_prob[samp]  # bootstrap probabilities
        yhat = y_pred[samp]  # bootstrap hard predictions

        aucs.append(roc_auc_score(yt, yp))  # compute AUROC
        f1 = precision_recall_fscore_support(yt, yhat, average="binary", zero_division=0)[2]  # F1
        f1s.append(f1)  # store F1

    def ci(x):  # helper to compute percentile CI
        return (np.percentile(x, 2.5), np.percentile(x, 97.5))

    return {  # return CIs
        "AUROC_CI": ci(aucs),
        "F1_CI": ci(f1s)
    }

# ============================================================
# Plot helpers (Classification) — all saved to CLS_DIR
# ============================================================

def plot_confusion(y_true, y_pred, title="Confusion Matrix", filename="confusion.png"):
    """
    Plot + save confusion matrix heatmap.
    """
    cm = confusion_matrix(y_true, y_pred)  # compute confusion matrix
    labels = ["Alive", "Dead"]  # labels
    plt.figure(figsize=(5, 4))  # create figure
    sns.heatmap(cm, annot=True, fmt="d", cmap="Oranges", cbar=True, xticklabels=labels, yticklabels=labels)  # heatmap with counts
    plt.xlabel("Predicted")  # x-axis label
    plt.ylabel("Actual")  # y-axis label
    plt.title(title)  # plot title
    save_current_fig(filename, CLS_DIR)  # save into classification folder
    plt.show()

def plot_roc_curve(y_true, y_prob, title="ROC Curve", filename="roc_curve.png"):
    """
    Plot + save ROC curve with AUROC.
    """
    fpr, tpr, _ = roc_curve(y_true, y_prob)  # compute ROC curve
    auc = roc_auc_score(y_true, y_prob)  # compute AUROC
    plt.figure(figsize=(6, 5))  # create figure
    plt.plot(fpr, tpr, label=f"AUROC = {auc:.3f}")  # ROC line
    plt.plot([0, 1], [0, 1], "--", color="gray")  # diagonal baseline
    plt.xlabel("False Positive Rate")  # x-axis label
    plt.ylabel("True Positive Rate")  # y-axis label
    plt.title(title)  # title
    plt.legend()  # legend
    save_current_fig(filename, CLS_DIR)  # save into classification folder
    plt.show()

def plot_combined_roc(roc_store, title="ROC Curves (Test Set)", filename="combined_roc.png"):
    """
    Plot + save combined ROC curves for all models.
    """
    plt.figure(figsize=(7, 6))  # create figure
    for name, (y_true, y_prob) in roc_store.items():  # iterate over models
        fpr, tpr, _ = roc_curve(y_true, y_prob)  # roc curve
        auc = roc_auc_score(y_true, y_prob)  # auroc
        plt.plot(fpr, tpr, label=f"{name} (AUROC={auc:.3f})")  # plot line
    plt.plot([0, 1], [0, 1], "--", color="gray")  # baseline
    plt.xlabel("False Positive Rate")  # x label
    plt.ylabel("True Positive Rate")  # y label
    plt.title(title)  # title
    plt.legend()  # legend
    save_current_fig(filename, CLS_DIR)  # save plot
    plt.show()

def plot_metric_bars_with_ci(res_df, metric_col, ci_col, title, filename="metric_bar_ci.png"):
    """
    Plot + save bar chart with CI error bars (e.g., AUROC or F1).
    """
    dfp = res_df.copy().sort_values(metric_col, ascending=False)  # sort models by metric

    means = dfp[metric_col].values  # metric values
    cis = dfp[ci_col].values  # CI tuples

    lower = np.array([c[0] for c in cis])  # CI lower bound
    upper = np.array([c[1] for c in cis])  # CI upper bound
    err_low = means - lower  # lower error
    err_high = upper - means  # upper error

    plt.figure(figsize=(8, 5))  # create figure
    plt.bar(dfp.index, means, yerr=[err_low, err_high], capsize=6, alpha=0.85)  # bar with error bars
    plt.ylabel(metric_col)  # y label
    plt.title(title)  # title
    plt.xticks(rotation=30, ha="right")  # rotate x labels
    save_current_fig(filename, CLS_DIR)  # save plot
    plt.show()

def plot_confusion_grid(cm_store, filename="confusion_grid.png"):
    """
    Plot + save confusion matrices for all models in a grid.
    """
    n = len(cm_store)  # number of models
    cols = 3  # fixed number of columns
    rows = int(np.ceil(n / cols))  # compute rows needed

    fig, axes = plt.subplots(rows, cols, figsize=(cols * 4.2, rows * 3.8))  # create subplots grid
    axes = np.array(axes).reshape(-1)  # flatten axes for easy indexing

    for ax, (name, (y_true, y_pred)) in zip(axes, cm_store.items()):  # loop through models
        cm = confusion_matrix(y_true, y_pred)  # confusion matrix
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=ax, cbar=False)  # plot heatmap
        ax.set_title(name)  # subplot title
        ax.set_xlabel("Predicted")  # x label
        ax.set_ylabel("Actual")  # y label

    for ax in axes[len(cm_store):]:  # hide unused subplots
        ax.axis("off")

    fig.tight_layout()  # tighten layout
    out_path = CLS_DIR / filename  # output path
    fig.savefig(out_path, dpi=200, bbox_inches="tight")  # save figure
    if SHOW_PLOTS:  # optionally show
        plt.show()
    plt.close(fig)  # close figure
    plt.show()

def learning_curve_plot(estimator, X, y, groups, title, filename="learning_curve.png"):
    """
    Plot + save learning curve: Train vs CV(Val) AUROC vs training set size.
    """
    train_sizes, train_scores, val_scores = learning_curve(  # run learning curve
        estimator, X, y,  # model + data
        cv=GroupKFold(n_splits=5),  # grouped CV (avoid patient leakage)
        groups=groups,  # groups array
        scoring="roc_auc",  # AUROC as score
        train_sizes=np.linspace(0.1, 1.0, 6),  # fractions of training data
        n_jobs=-1  # use all cores
    )
    train_mean = train_scores.mean(axis=1)  # mean train score per size
    val_mean = val_scores.mean(axis=1)  # mean val score per size

    plt.figure(figsize=(6, 5))  # create figure
    plt.plot(train_sizes, train_mean, marker="o", label="Train AUROC")  # train curve
    plt.plot(train_sizes, val_mean, marker="o", label="Val AUROC")  # val curve
    plt.title(title)  # title
    plt.xlabel("Training examples")  # x label
    plt.ylabel("AUROC")  # y label
    plt.legend()  # legend
    save_current_fig(filename, CLS_DIR)  # save into classification folder
    plt.show()

def plot_pr_curve(y_true, y_prob, title="Precision-Recall Curve", filename="pr_curve.png"):
    """
    Plot + save Precision-Recall (PR) curve with Average Precision (AUPRC).
    """
    precision, recall, _ = precision_recall_curve(y_true, y_prob)
    auprc = average_precision_score(y_true, y_prob)
    plt.figure(figsize=(6, 5))
    # PR curves are Recall on x-axis, Precision on y-axis
    plt.plot(recall, precision, label=f"AUPRC = {auprc:.3f}")
    # Baseline: horizontal line at prevalence (optional, but helpful)
    prevalence = np.mean(y_true)
    plt.axhline(prevalence, ls="--", color="gray", label=f"Prevalence = {prevalence:.3f}")
    plt.xlabel("Recall")
    plt.ylabel("Precision")
    plt.title(title)
    plt.legend()
    save_current_fig(filename, CLS_DIR)
    plt.show()


# ============================================================
# Ethnicity subgroup analysis helpers (classification plots saved to CLS_DIR)
# ============================================================

def collapse_ethnicity(series: pd.Series, min_count=50) -> pd.Series:
    """
    Collapses rare ethnicity categories into 'Other'.
    """
    s = series.replace("", np.nan).fillna("Unknown").astype(str)  # normalize blanks
    counts = s.value_counts()  # count occurrences
    rare = counts[counts < min_count].index  # categories below threshold
    s = s.where(~s.isin(rare), "Other")  # replace rare with Other
    return s  # return collapsed series

def bootstrap_ci_auc_f1_by_group(y_true, y_prob, y_pred, n_boot=2000, seed=42):
    """
    Bootstrap CI within subgroup for AUROC and F1.
    """
    y_true = np.asarray(y_true)  # ensure array
    y_prob = np.asarray(y_prob)  # ensure array
    y_pred = np.asarray(y_pred)  # ensure array

    if len(np.unique(y_true)) < 2:  # need both classes for AUROC
        return (None, None)

    rng = np.random.default_rng(seed)  # reproducible RNG
    aucs, f1s = [], []  # store bootstrap metrics
    idxs = np.arange(len(y_true))  # indices for sampling

    for _ in range(n_boot):  # bootstrap loop
        b = rng.choice(idxs, size=len(idxs), replace=True)  # resample indices
        yt = y_true[b]  # bootstrap labels
        if len(np.unique(yt)) < 2:  # skip if only one class in sample
            continue
        yp = y_prob[b]  # bootstrap probs
        yhat = y_pred[b]  # bootstrap preds
        aucs.append(roc_auc_score(yt, yp))  # AUROC
        f1s.append(precision_recall_fscore_support(yt, yhat, average="binary", zero_division=0)[2])  # F1

    if len(aucs) < 50:  # not enough valid bootstraps
        return (None, None)

    auc_ci = (np.percentile(aucs, 2.5), np.percentile(aucs, 97.5))  # AUROC CI
    f1_ci = (np.percentile(f1s, 2.5), np.percentile(f1s, 97.5))  # F1 CI
    return (auc_ci, f1_ci)  # return both

def subgroup_classification_report(y_true, y_prob, y_pred, group_labels, min_n=50, min_pos=10):
    """
    Compute subgroup metrics per ethnicity group.
    """
    y_true = np.asarray(y_true)  # array labels
    y_prob = np.asarray(y_prob)  # array probabilities
    y_pred = np.asarray(y_pred)  # array hard preds
    group_labels = pd.Series(group_labels).fillna("Unknown").astype(str).values  # group labels

    rows = []  # store subgroup rows
    for g in pd.Series(group_labels).unique():  # loop group names
        mask = (group_labels == g)  # mask group subset
        n = int(mask.sum())  # sample size
        if n < min_n:  # skip small groups
            continue

        yt = y_true[mask]  # subgroup y
        yp = y_prob[mask]  # subgroup prob
        yhat = y_pred[mask]  # subgroup pred

        pos = int((yt == 1).sum())  # subgroup positives
        neg = int((yt == 0).sum())  # subgroup negatives
        prev = pos / n if n > 0 else np.nan  # prevalence

        if pos < min_pos or neg < 1:  # too few positives
            auc = np.nan  # undefined
            auprc = np.nan  # undefined
            auc_ci, f1_ci = (None, None)  # no CI
        else:
            auc = roc_auc_score(yt, yp)  # subgroup AUROC
            auprc = average_precision_score(yt, yp)  # subgroup AUPRC
            auc_ci, f1_ci = bootstrap_ci_auc_f1_by_group(yt, yp, yhat)  # bootstrap CIs

        prec, rec, f1, _ = precision_recall_fscore_support(yt, yhat, average="binary", zero_division=0)  # P/R/F1

        rows.append({  # store row
            "ethnicity": g,
            "n": n,
            "positives": pos,
            "prevalence": prev,
            "AUROC": auc,
            "AUPRC": auprc,
            "Precision": prec,
            "Recall": rec,
            "F1": f1,
            "AUROC_95CI": auc_ci,
            "F1_95CI": f1_ci
        })

    return pd.DataFrame(rows).sort_values(["AUROC", "F1"], ascending=False)  # output dataframe sorted

def plot_subgroup_metric(df_sub, metric="AUROC", ci_col="AUROC_95CI", title="Metric by Ethnicity", filename="subgroup_metric.png"):
    """
    Plot + save subgroup metric bars with CI.
    """
    dfp = df_sub.dropna(subset=[metric]).copy().sort_values(metric, ascending=False)  # valid rows only
    if dfp.empty:  # nothing to plot
        return

    means = dfp[metric].values  # metric means
    cis = dfp[ci_col].values  # CI tuples

    lower = np.array([c[0] if c is not None else np.nan for c in cis])  # lower bounds
    upper = np.array([c[1] if c is not None else np.nan for c in cis])  # upper bounds
    err_low = means - lower  # lower error
    err_high = upper - means  # upper error

    plt.figure(figsize=(10, 5))  # figure
    plt.bar(dfp["ethnicity"], means, yerr=[err_low, err_high], capsize=5, alpha=0.85)  # bars + CI
    plt.xticks(rotation=35, ha="right")  # rotate labels
    plt.ylabel(metric)  # y label
    plt.title(title)  # title
    save_current_fig(filename, CLS_DIR)  # save
    plt.show()

def plot_roc_by_ethnicity(y_true, y_prob, group_labels, min_n=50, min_pos=10, title="ROC by Ethnicity", filename="roc_by_ethnicity.png"):
    """
    Plot + save ROC curves for each ethnicity group (if enough samples).
    """
    y_true = np.asarray(y_true)  # true labels
    y_prob = np.asarray(y_prob)  # predicted probabilities
    g = pd.Series(group_labels).fillna("Unknown").astype(str).values  # group labels

    plt.figure(figsize=(8, 7))  # figure
    for grp in pd.Series(g).unique():  # loop groups
        mask = (g == grp)  # group mask
        n = int(mask.sum())  # group size
        if n < min_n:  # skip too small
            continue
        yt = y_true[mask]  # subgroup labels
        yp = y_prob[mask]  # subgroup probs
        pos = int((yt == 1).sum())  # subgroup positives
        neg = int((yt == 0).sum())  # subgroup negatives
        if pos < min_pos or neg < 1:  # skip if too few positives
            continue
        fpr, tpr, _ = roc_curve(yt, yp)  # roc curve
        auc = roc_auc_score(yt, yp)  # subgroup auc
        plt.plot(fpr, tpr, label=f"{grp} (n={n}, AUC={auc:.3f})")  # line

    plt.plot([0, 1], [0, 1], "--", color="gray")  # baseline
    plt.xlabel("False Positive Rate")  # x label
    plt.ylabel("True Positive Rate")  # y label
    plt.title(title)  # title
    plt.legend(fontsize=9)  # legend
    save_current_fig(filename, CLS_DIR)  # save


# ============================================================
# Data Loading + Aggregation
# ============================================================

df = pd.read_csv("/content/drive/MyDrive/EHR/dx_encoded_feats.csv")  # load processed dataset

required = ["subject_id", "hadm_id", "hospital_expire_flag", "los_days"]  # required columns
missing = [c for c in required if c not in df.columns]  # check missing columns
if missing:  # if missing required columns
    raise ValueError(f"Missing required columns: {missing}")  # raise error

if "race" not in df.columns:  # race needed for ethnicity subgroup analysis
    raise ValueError("Column 'race' not found. Needed for ethnicity subgroup analysis.")  # raise error

# Parse CCSR list column into actual lists
if "ccsr_list_sorted" in df.columns:  # if exists
    df["ccsr_list_sorted"] = df["ccsr_list_sorted"].apply(parse_list_cell)  # parse lists
else:
    df["ccsr_list_sorted"] = [[] for _ in range(len(df))]  # fallback empty lists

# Aggregate to admission-level (one row per hadm_id)
agg_dict = {}  # column -> aggregation strategy
for col in df.columns:  # loop all columns
    if col == "ccsr_list_sorted":  # skip list column (handled separately)
        continue
    agg_dict[col] = "first"  # assume admission-level constant per hadm_id

df_adm = df.groupby("hadm_id", as_index=False).agg(agg_dict)  # admission-level dataframe

# Union CCSR codes across diagnosis rows within an admission
ccsr_union = df.groupby("hadm_id")["ccsr_list_sorted"].apply(lambda rows: sorted(set(sum(rows, []))))  # unique list per hadm_id
df_adm = df_adm.merge(ccsr_union.rename("ccsr_union"), on="hadm_id", how="left")  # merge into df_adm
df_adm["n_ccsr_unique"] = df_adm["ccsr_union"].apply(lambda x: len(x) if isinstance(x, list) else 0)  # feature: number of unique CCSR codes

# Extra feature: number of diagnosis rows (proxy for diagnostic complexity)
n_dx = df.groupby("hadm_id").size().rename("n_dx_rows").reset_index()  # count rows per hadm_id
df_adm = df_adm.merge(n_dx, on="hadm_id", how="left")  # merge

# ============================================================
# Feature Matrix Construction
# ============================================================

exclude = {  # exclude targets, identifiers, and leakage columns
    "hospital_expire_flag", "los_days", "los_hours",
    "dischtime", "deathtime", "dischtime_dt", "deathtime_dt",
    "admittime", "admittime_dt",
    "hadm_id", "subject_id",
    "ccsr_list_sorted", "ccsr_union", "ccsr_description"
}

numeric_cols = []  # list of numeric feature column names
for c in df_adm.columns:  # loop all columns
    if c in exclude:  # skip excluded columns
        continue
    if pd.api.types.is_numeric_dtype(df_adm[c]):  # keep numeric columns
        numeric_cols.append(c)
    if c.endswith("_code") or c in [  # also keep known engineered numeric columns
        "age_at_admit", "adm_year", "adm_month", "adm_day", "adm_hour",
        "adm_weekday", "adm_weekend", "n_ccsr_unique", "n_dx_rows"
    ]:
        numeric_cols.append(c)

numeric_cols = sorted(set(numeric_cols))  # unique and sorted

X_num = df_adm[numeric_cols].apply(pd.to_numeric, errors="coerce")  # numeric matrix (with NaNs)

mlb = MultiLabelBinarizer(sparse_output=True)  # multi-hot encoder for CCSR categories
X_ccsr = mlb.fit_transform(df_adm["ccsr_union"])  # sparse multi-hot matrix

X = sparse.hstack([sparse.csr_matrix(X_num.values), X_ccsr]).tocsr()  # combine numeric + CCSR into one sparse matrix

y_cls = df_adm["hospital_expire_flag"].astype(int).values  # classification labels
y_reg = pd.to_numeric(df_adm["los_days"], errors="coerce").values  # regression target
groups = df_adm["subject_id"].values  # patient-level groups
reg_mask = np.isfinite(y_reg)  # mask for regression rows with valid los_days

# ============================================================
# Patient-grouped Train / Val / Test Split
# ============================================================

gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)  # group split for test set
train_idx, test_idx = next(gss.split(X, y_cls, groups=groups))  # indices

X_train, X_test = X[train_idx], X[test_idx]  # train/test matrices
y_train, y_test = y_cls[train_idx], y_cls[test_idx]  # train/test labels
groups_train = groups[train_idx]  # group labels for train set

gss2 = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=7)  # group split for validation
tr2_idx, val_idx = next(gss2.split(X_train, y_train, groups=groups_train))  # indices for train/val inside train

X_tr, X_val = X_train[tr2_idx], X_train[val_idx]  # train/val matrices
y_tr, y_val = y_train[tr2_idx], y_train[val_idx]  # train/val labels

# Dense matrices for models that require/benefit from dense (CatBoost, DecisionTree)
X_train_d = X_train.toarray()  # dense train
X_test_d = X_test.toarray()  # dense test
X_tr_d = X_tr.toarray()  # dense training fold
X_val_d = X_val.toarray()  # dense validation fold

# Ethnicity labels aligned to test set (collapsed for stability)
eth_test_raw = df_adm.iloc[test_idx]["race"]  # raw race labels
eth_test = collapse_ethnicity(eth_test_raw, min_count=50).values  # collapsed ethnicity labels

# ============================================================
# Models (Classification)
# ============================================================

pos = int((y_tr == 1).sum())  # number of positives in training fold
neg = int((y_tr == 0).sum())  # number of negatives in training fold
pos_weight = neg / max(1, pos)  # imbalance weight for XGBoost

models_cls = {  # dictionary of classification models
    "LogReg": Pipeline(steps=[  # Logistic Regression pipeline
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler(with_mean=False)),  # scale sparse
        ("clf", LogisticRegression(max_iter=5000, class_weight="balanced", n_jobs=-1))  # classifier
    ]),

    "SVM": Pipeline(steps=[  # SVM pipeline
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler(with_mean=False)),  # scale sparse
        ("clf", SVC(kernel="rbf", probability=True, class_weight="balanced"))  # SVC classifier
    ]),

    "XGBoost": XGBClassifier(  # XGBoost classifier
        n_estimators=2000, learning_rate=0.03, max_depth=6,  # basic params
        subsample=0.8, colsample_bytree=0.8,  # sampling for regularization
        reg_lambda=1.0, eval_metric="auc",  # L2 regularization and eval metric
        early_stopping_rounds=100,  # stop when val AUC stops improving
        scale_pos_weight=pos_weight,  # handle imbalance
        tree_method="hist",  # faster tree building
        random_state=42  # reproducibility
    ),

    "RandomForest": Pipeline(steps=[  # Random Forest pipeline
        ("imputer", SimpleImputer(strategy="median")),
        ("clf", RandomForestClassifier(
            n_estimators=500,
            random_state=42,
            class_weight="balanced",
            n_jobs=-1
        ))
    ]),

    "DecisionTree": Pipeline(steps=[  # Decision Tree pipeline
        ("imputer", SimpleImputer(strategy="median")),
        ("clf", DecisionTreeClassifier(  # tree classifier
            random_state=42,  # reproducibility
            class_weight="balanced",  # handle imbalance
            max_depth=None,  # allow full depth (can overfit)
            min_samples_leaf=10  # regularization to reduce overfitting
        ))
    ]),
    "LightGBM": lgb.LGBMClassifier(  # LightGBM classifier
        n_estimators=5000, learning_rate=0.03,
        num_leaves=63, subsample=0.8, colsample_bytree=0.8,  # tree complexity
        class_weight="balanced",  # handle imbalance
        random_state=42  # reproducibility
    ),
    "CatBoost": CatBoostClassifier(  # CatBoost classifier
        iterations=5000, learning_rate=0.03, depth=6,  # boosting params
        loss_function="Logloss", eval_metric="AUC",  # objective and eval metric
        custom_metric=["AUC"],  # store AUC in logs
        random_seed=42,  # reproducibility
        verbose=False  # silence training logs
    )
}

# ============================================================
# Train + Evaluate Classification
# ============================================================
pr_store = {}  # store (y_true, y_prob) for combined PR plot
results_cls = {}  # store overall model metrics
roc_store = {}  # store (y_true, y_prob) for combined ROC plot
cm_store = {}  # store (y_true, y_pred) for confusion grid
per_model_preds = {}  # store predictions for subgroup analysis

for name, model in models_cls.items():  # iterate models
    print(f"\n===== Training {name} (Classification) =====")  # progress message
    tag = _safe_name(name)  # safe filename tag

    # --- XGBoost training + train/val curve ---
    if name == "XGBoost":
        model.fit(  # train xgboost
            X_tr, y_tr,  # training fold
            eval_set=[(X_tr, y_tr), (X_val, y_val)],  # evaluate on train and val
            verbose=False  # silent training
        )
        evals = model.evals_result()  # training logs
        plt.figure(figsize=(6, 4))  # figure
        plt.plot(evals["validation_0"]["auc"], label="Train AUC")  # train curve
        plt.plot(evals["validation_1"]["auc"], label="Val AUC")  # val curve
        plt.title(f"{name}: Train/Val AUC vs Iteration")  # title
        plt.xlabel("Iteration")  # x label
        plt.ylabel("AUC")  # y label
        plt.legend()  # legend
        save_current_fig(f"{tag}_train_val_auc_curve.png", CLS_DIR)  # save

    # --- LightGBM training + train/val curve ---
    elif name == "LightGBM":
        model.fit(  # train lgbm
            X_tr, y_tr,  # train fold
            eval_set=[(X_tr, y_tr), (X_val, y_val)],  # train and val monitoring
            eval_metric="auc",  # metric
            callbacks=[  # early stopping and periodic logging
                lgb.early_stopping(stopping_rounds=100, verbose=False),
                lgb.log_evaluation(period=50)
            ],
        )
        evals = model.evals_result_  # training logs
        plt.figure(figsize=(6, 4))  # figure
        plt.plot(evals["training"]["auc"], label="Train AUC")  # train auc
        plt.plot(evals["valid_1"]["auc"], label="Val AUC")  # val auc
        plt.title(f"{name}: Train/Val AUC vs Iteration")  # title
        plt.xlabel("Iteration")  # x label
        plt.ylabel("AUC")  # y label
        plt.legend()  # legend
        save_current_fig(f"{tag}_train_val_auc_curve.png", CLS_DIR)  # save

    # --- CatBoost training + train/val curve ---
    elif name == "CatBoost":
        model.fit(  # train catboost
            X_tr_d, y_tr,  # dense train fold
            eval_set=(X_val_d, y_val),  # dense val
            use_best_model=True,  # use best iteration
            verbose=False  # silence
        )
        evals = model.get_evals_result()  # training logs

        # helper to find AUC key (sometimes "AUC:type=Classic")
        def find_metric_key(metric_dict, target="AUC"):
            keys = list(metric_dict.keys())  # all metric keys
            if target in keys:  # direct match
                return target
            for k in keys:  # search substring match
                if target.upper() in k.upper():
                    return k
            return None

        val_block = evals.get("validation", None) or evals.get("validation_0", None)  # validation block
        learn_block = evals.get("learn", None)  # training block

        if val_block is not None and learn_block is not None:  # if blocks exist
            auc_key_val = find_metric_key(val_block, "AUC")  # metric key in val
            auc_key_learn = find_metric_key(learn_block, "AUC")  # metric key in train

            plt.figure(figsize=(6, 4))  # figure
            if auc_key_val is not None:  # plot val auc if exists
                plt.plot(val_block[auc_key_val], label=f"Val {auc_key_val}")
            if auc_key_learn is not None:  # plot train auc if exists
                plt.plot(learn_block[auc_key_learn], label=f"Train {auc_key_learn}")
            plt.title(f"{name}: Train/Val AUC vs Iteration")  # title
            plt.xlabel("Iteration")  # x label
            plt.ylabel("Metric value")  # y label
            plt.legend()  # legend
            save_current_fig(f"{tag}_train_val_auc_curve.png", CLS_DIR)  # save

    # --- LR / SVM / DecisionTree training + learning curve ---
    else:
        if name in ["DecisionTree", "RandomForest"]:  # decision tree / random forest uses dense for speed
            model.fit(X_tr_d, y_tr)  # fit on dense
            learning_curve_plot(  # save learning curve
                model, X_train_d, y_train, groups_train,
                f"{name}: Learning Curve (AUROC)",
                filename=f"{tag}_learning_curve_auc.png"
            )
        else:  # LR/SVM works with sparse
            model.fit(X_tr, y_tr)  # fit model
            learning_curve_plot(  # save learning curve
                model, X_train, y_train, groups_train,
                f"{name}: Learning Curve (AUROC)",
                filename=f"{tag}_learning_curve_auc.png"
            )

    # ----------------------------
    # Predict on test set
    # ----------------------------
    if name == "CatBoost":  # catboost requires dense
        y_prob = model.predict_proba(X_test_d)[:, 1]  # probabilities
    elif name in ["DecisionTree", "RandomForest"]:  # tree/forest uses dense (pipeline has imputer inside)
        y_prob = model.predict_proba(X_test_d)[:, 1]  # probabilities
    else:  # all other models accept sparse
        y_prob = model.predict_proba(X_test)[:, 1]  # probabilities

    y_pred = (y_prob >= 0.5).astype(int)  # threshold into hard labels

    # ----------------------------
    # Compute metrics
    # ----------------------------
    auc = roc_auc_score(y_test, y_prob)  # test AUROC
    auprc = average_precision_score(y_test, y_prob)  # test AUPRC
    prec, rec, f1, _ = precision_recall_fscore_support(y_test, y_pred, average="binary", zero_division=0)  # P/R/F1
    ci = bootstrap_ci_classification(y_test, y_prob, y_pred)  # bootstrap CIs

    print(classification_report(y_test, y_pred, digits=4))  # report

    # ----------------------------
    # Save per-model plots
    # ----------------------------
    plot_confusion(  # confusion matrix
        y_test, y_pred,
        title=f"{name} Confusion Matrix (Test)",
        filename=f"{tag}_confusion_matrix_test.png"
    )
    plot_roc_curve(  # ROC curve
        y_test, y_prob,
        title=f"{name} ROC Curve (Test)",
        filename=f"{tag}_roc_curve_test.png"
    )

    # ----------------------------
    # Store for later combined plots and subgroup analysis
    # ----------------------------
    roc_store[name] = (y_test, y_prob)  # store for combined ROC
    cm_store[name] = (y_test, y_pred)  # store for confusion grid
    per_model_preds[name] = {"y_prob": y_prob, "y_pred": y_pred}  # store for subgroup

    # ----------------------------
    # Store summary results
    # ----------------------------
    results_cls[name] = {
        "AUROC": auc,
        "AUPRC": auprc,
        "Precision": prec,
        "Recall": rec,
        "F1": f1,
        "AUROC_95CI": ci["AUROC_CI"],
        "F1_95CI": ci["F1_CI"]
    }


# ----------------------------
# Print summary table
# ----------------------------
res_df = pd.DataFrame(results_cls).T.sort_values("AUROC", ascending=False)  # summary dataframe
print("\n=== Classification Performance Summary (Test) ===")  # header
print(res_df)  # print

# ----------------------------
# Save overall comparison plots
# ----------------------------
plot_combined_roc(roc_store,
                  title="ROC Curves (All Models, Test Set)",
                  filename="all_models_combined_roc.png")  # save

plot_confusion_grid(cm_store,
                    filename="all_models_confusion_grid.png")  # save grid

plot_metric_bars_with_ci(res_df,
                         "AUROC",
                         "AUROC_95CI",
                         "AUROC with 95% CI (Test Set)", filename="all_models_auroc_ci.png")  # save

plot_metric_bars_with_ci(res_df,
                         "F1",
                         "F1_95CI", "F1 with 95% CI (Test Set)", filename="all_models_f1_ci.png")  # save


# ============================================================
# Ethnicity subgroup analysis (Mortality)
# ============================================================

print("\n==============================")  # separator
print(" Ethnicity subgroup evaluation ")  # header
print("==============================")  # separator

subgroup_tables = {}  # store subgroup tables per model
for name, pred in per_model_preds.items():  # loop models
    tag = _safe_name(name)  # safe tag
    y_prob = pred["y_prob"]  # probs
    y_pred = pred["y_pred"]  # hard preds

    df_sub = subgroup_classification_report(  # compute subgroup report
        y_true=y_test,
        y_prob=y_prob,
        y_pred=y_pred,
        group_labels=eth_test,
        min_n=50,
        min_pos=10
    )
    subgroup_tables[name] = df_sub  # store table
    print(f"\n--- {name}: subgroup metrics (test set) ---")  # print header
    print(df_sub)  # print subgroup table

    # Save subgroup plots if enough groups exist
    if len(df_sub) >= 2:
        plot_subgroup_metric(  # AUROC by ethnicity
            df_sub, metric="AUROC", ci_col="AUROC_95CI",
            title=f"{name}: AUROC by Ethnicity (Test Set)",
            filename=f"{tag}_ethnicity_auroc_ci.png"
        )
        plot_subgroup_metric(  # F1 by ethnicity
            df_sub, metric="F1", ci_col="F1_95CI",
            title=f"{name}: F1 by Ethnicity (Test Set)",
            filename=f"{tag}_ethnicity_f1_ci.png"
        )
        plot_roc_by_ethnicity(  # ROC curves per ethnicity
            y_test, y_prob, eth_test,
            min_n=50, min_pos=10,
            title=f"{name}: ROC Curves by Ethnicity (Test Set)",
            filename=f"{tag}_ethnicity_roc.png"
        )

# ============================================================
# Regression Models (LOS)
# ============================================================

# Filter data for regression only (valid LOS rows)
Xr = X[reg_mask]  # regression feature matrix
yr = y_reg[reg_mask]  # regression target
gr = groups[reg_mask]  # patient groups for regression

# Ethnicity aligned to regression rows
eth_all = collapse_ethnicity(df_adm["race"], min_count=50).values  # ethnicity for all rows
eth_r = eth_all[reg_mask]  # ethnicity for regression rows

# Grouped train/test split for regression
train_idx_r, test_idx_r = next(
    GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42).split(Xr, yr, groups=gr)
)
X_train_r, X_test_r = Xr[train_idx_r], Xr[test_idx_r]  # regression train/test matrices
y_train_r, y_test_r = yr[train_idx_r], yr[test_idx_r]  # regression targets
groups_train_r = gr[train_idx_r]  # groups for regression train set

# Grouped train/val split within regression training set
tr2_idx_r, val_idx_r = next(
    GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=7).split(X_train_r, y_train_r, groups=groups_train_r)
)
X_tr_r, X_val_r = X_train_r[tr2_idx_r], X_train_r[val_idx_r]  # train/val
y_tr_r, y_val_r = y_train_r[tr2_idx_r], y_train_r[val_idx_r]  # train/val targets

# Log-transform LOS targets (stabilizes heavy right-skew)
y_tr_log = np.log1p(y_tr_r)  # log(1 + LOS)
y_val_log = np.log1p(y_val_r)  # log(1 + LOS)

# Dense versions for models requiring dense
X_train_r_d = X_train_r.toarray()  # dense train
X_test_r_d = X_test_r.toarray()  # dense test
X_tr_r_d = X_tr_r.toarray()  # dense train fold
X_val_r_d = X_val_r.toarray()  # dense val fold

# Regression model dictionary
models_reg = {
    "SVR": Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler(with_mean=False)),
        ("reg", SVR(C=10.0, gamma="scale", epsilon=0.1))
    ]),

    "XGBoost": XGBRegressor(
        n_estimators=5000, learning_rate=0.03, max_depth=6,
        subsample=0.8, colsample_bytree=0.8,
        reg_lambda=1.0,
        objective="reg:squarederror",
        eval_metric="rmse",
        early_stopping_rounds=100,
        tree_method="hist",
        random_state=42
    ),

    "DecisionTree": Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("reg", DecisionTreeRegressor(
            random_state=42,
            max_depth=None,
            min_samples_leaf=10
        ))
    ]),


    "RandomForest": Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("reg", RandomForestRegressor(
            n_estimators=500,
            random_state=42,
            n_jobs=-1
        ))
    ]),


    "LightGBM": lgb.LGBMRegressor(
        n_estimators=5000, learning_rate=0.03,
        num_leaves=63, subsample=0.8, colsample_bytree=0.8,
        random_state=42
    ),
    "CatBoost": CatBoostRegressor(
        iterations=5000, learning_rate=0.03, depth=6,
        loss_function="RMSE",
        random_seed=42, verbose=False
    )
}

results_reg = {}  # store regression metrics
preds_reg = {}  # store predictions for subgroup analysis

for name, model in models_reg.items():  # loop regression models
    print(f"\n===== Training {name} (Regression LOS) =====")  # progress message
    tag = _safe_name(name)  # safe filename tag

    if name == "XGBoost":  # xgboost regressor
        model.fit(  # fit model
            X_tr_r, y_tr_log,
            eval_set=[(X_tr_r, y_tr_log), (X_val_r, y_val_log)],
            verbose=False
        )
        evals = model.evals_result()  # training logs
        plt.figure(figsize=(6, 4))  # figure
        plt.plot(evals["validation_0"]["rmse"], label="Train RMSE")  # train curve
        plt.plot(evals["validation_1"]["rmse"], label="Val RMSE")  # val curve
        plt.title(f"{name}: Train/Val RMSE vs Iteration (log1p LOS)")  # title
        plt.xlabel("Iteration")  # x label
        plt.ylabel("RMSE")  # y label
        plt.legend()  # legend
        save_current_fig(f"{tag}_train_val_rmse_curve.png", REG_DIR)  # save to regression folder

    elif name == "LightGBM":  # lightgbm regressor
        model.fit(  # fit model
            X_tr_r, y_tr_log,
            eval_set=[(X_tr_r, y_tr_log), (X_val_r, y_val_log)],
            eval_metric="rmse",
            callbacks=[
                lgb.early_stopping(stopping_rounds=100, verbose=True),
                lgb.log_evaluation(period=50)
            ]
        )
        evals = model.evals_result_  # training logs
        plt.figure(figsize=(6, 4))  # figure
        plt.plot(evals["training"]["rmse"], label="Train RMSE")  # train curve
        plt.plot(evals["valid_1"]["rmse"], label="Val RMSE")  # val curve
        plt.title(f"{name}: Train/Val RMSE vs Iteration (log1p LOS)")  # title
        plt.xlabel("Iteration")  # x label
        plt.ylabel("RMSE")  # y label
        plt.legend()  # legend
        save_current_fig(f"{tag}_train_val_rmse_curve.png", REG_DIR)  # save

    elif name == "CatBoost":  # catboost regressor
        model.fit(  # fit model
            X_tr_r_d, y_tr_log,
            eval_set=(X_val_r_d, y_val_log),
            use_best_model=True
        )
        evals = model.get_evals_result()  # logs
        plt.figure(figsize=(6, 4))  # figure
        plt.plot(evals["learn"]["RMSE"], label="Train RMSE")  # train curve
        plt.plot(evals["validation"]["RMSE"], label="Val RMSE")  # val curve
        plt.title(f"{name}: Train/Val RMSE vs Iteration (log1p LOS)")  # title
        plt.xlabel("Iteration")  # x label
        plt.ylabel("RMSE")  # y label
        plt.legend()  # legend
        save_current_fig(f"{tag}_train_val_rmse_curve.png", REG_DIR)  # save

    else:  # SVR / DecisionTree (non-iterative)
        if name in ["DecisionTree", "RandomForest"]:  # tree/forest uses dense
            model.fit(X_tr_r_d, y_tr_log)  # fit on dense
        else:
            model.fit(X_tr_r, y_tr_log)  # fit on sparse

    # Predict log-space LOS, then invert back to days
    if name == "CatBoost":
        yhat_log = model.predict(X_test_r_d)  # dense predict
    elif name in ["DecisionTree", "RandomForest"]:  # tree/forest uses dense
        yhat_log = model.predict(X_test_r_d)  # dense predict
    else:
        yhat_log = model.predict(X_test_r)  # sparse predict

    yhat = np.expm1(yhat_log)  # invert log1p to days
    yhat = np.clip(yhat, 0, None)  # ensure no negative predictions

    mae = mean_absolute_error(y_test_r, yhat)  # MAE in days
    rmse = mean_squared_error(y_test_r, yhat, squared=False)  # RMSE in days
    r2 = r2_score(y_test_r, yhat)  # R2

    results_reg[name] = {"MAE": mae, "RMSE": rmse, "R2": r2}  # store metrics
    preds_reg[name] = yhat  # store predictions

print("\n=== Regression Performance Summary (Test, LOS days) ===")  # header
reg_df = pd.DataFrame(results_reg).T.sort_values("RMSE")  # summary df sorted by RMSE
print(reg_df)  # print

# Save regression comparison plots
plt.figure(figsize=(8, 5))  # figure
plt.bar(reg_df.index, reg_df["RMSE"], color="darkorange", alpha=0.85)  # bars
plt.ylabel("RMSE (days)")  # label
plt.title("LOS Regression: RMSE by Model (Test Set)")  # title
plt.xticks(rotation=30, ha="right")  # rotate
save_current_fig("los_rmse_by_model.png", REG_DIR)  # save

plt.figure(figsize=(8, 5))  # figure
plt.bar(reg_df.index, reg_df["MAE"], color="seagreen", alpha=0.85)  # bars
plt.ylabel("MAE (days)")  # label
plt.title("LOS Regression: MAE by Model (Test Set)")  # title
plt.xticks(rotation=30, ha="right")  # rotate
save_current_fig("los_mae_by_model.png", REG_DIR)  # save

# ============================================================
# Ethnicity subgroup analysis for LOS regression (saved to REG_DIR)
# ============================================================

eth_test_r = eth_r[test_idx_r]  # ethnicity labels for regression test set

def subgroup_regression_report(y_true, y_pred, group_labels, min_n=50, n_boot=2000, seed=42):
    """
    Compute subgroup MAE/RMSE/R2 + bootstrap CIs for MAE and RMSE.
    """
    y_true = np.asarray(y_true)  # true values
    y_pred = np.asarray(y_pred)  # predictions
    g = pd.Series(group_labels).fillna("Unknown").astype(str).values  # group labels

    rng = np.random.default_rng(seed)  # RNG
    rows = []  # results

    for grp in pd.Series(g).unique():  # loop groups
        mask = (g == grp)  # mask
        n = int(mask.sum())  # group size
        if n < min_n:  # skip small groups
            continue

        yt = y_true[mask]  # true subgroup
        yp = y_pred[mask]  # pred subgroup

        mae = mean_absolute_error(yt, yp)  # MAE
        rmse = mean_squared_error(yt, yp, squared=False)  # RMSE
        r2 = r2_score(yt, yp)  # R2

        idxs = np.arange(n)  # indices
        mae_boot, rmse_boot = [], []  # store bootstraps

        for _ in range(n_boot):  # bootstrap loop
            b = rng.choice(idxs, size=n, replace=True)  # resample
            mae_boot.append(mean_absolute_error(yt[b], yp[b]))  # bootstrap MAE
            rmse_boot.append(mean_squared_error(yt[b], yp[b], squared=False))  # bootstrap RMSE

        mae_ci = (np.percentile(mae_boot, 2.5), np.percentile(mae_boot, 97.5))  # MAE CI
        rmse_ci = (np.percentile(rmse_boot, 2.5), np.percentile(rmse_boot, 97.5))  # RMSE CI

        rows.append({  # store row
            "ethnicity": grp,
            "n": n,
            "MAE": mae,
            "MAE_95CI": mae_ci,
            "RMSE": rmse,
            "RMSE_95CI": rmse_ci,
            "R2": r2
        })

    return pd.DataFrame(rows).sort_values("RMSE")  # sorted table

def plot_subgroup_regression_metric(df_sub, metric="RMSE", ci_col="RMSE_95CI", title="LOS Error by Ethnicity", filename="los_ethnicity_metric.png"):
    """
    Plot + save subgroup regression metric bars with CI.
    """
    dfp = df_sub.copy()  # copy table
    means = dfp[metric].values  # means
    cis = dfp[ci_col].values  # CIs
    lower = np.array([c[0] for c in cis])  # lower bound
    upper = np.array([c[1] for c in cis])  # upper bound
    err_low = means - lower  # lower error
    err_high = upper - means  # upper error

    plt.figure(figsize=(10, 5))  # figure
    plt.bar(dfp["ethnicity"], means, yerr=[err_low, err_high], capsize=5, alpha=0.85)  # bars
    plt.xticks(rotation=35, ha="right")  # rotate labels
    plt.ylabel(metric)  # y label
    plt.title(title)  # title
    save_current_fig(filename, REG_DIR)  # save to regression folder

print("\n==============================")  # header separator
print(" Ethnicity subgroup (LOS)      ")  # header
print("==============================")  # separator

for name, yhat in preds_reg.items():  # loop models
    tag = _safe_name(name)  # safe name
    df_sub_r = subgroup_regression_report(y_test_r, yhat, eth_test_r, min_n=50)  # subgroup report
    print(f"\n--- {name}: LOS subgroup metrics ---")  # print header
    print(df_sub_r)  # print table

    if len(df_sub_r) >= 2:  # only plot if more than one group
        plot_subgroup_regression_metric(  # RMSE by ethnicity
            df_sub_r, metric="RMSE", ci_col="RMSE_95CI",
            title=f"{name}: RMSE by Ethnicity (Test Set)",
            filename=f"{tag}_ethnicity_rmse_ci.png"
        )
        plot_subgroup_regression_metric(  # MAE by ethnicity
            df_sub_r, metric="MAE", ci_col="MAE_95CI",
            title=f"{name}: MAE by Ethnicity (Test Set)",
            filename=f"{tag}_ethnicity_mae_ci.png"
        )

print("\nDone. Plots saved under:")
print(" -", CLS_DIR.resolve())
print(" -", REG_DIR.resolve())

# Append code for comparative ROC curves for XGBoost, SVM, and LogReg
filtered_roc_store = {
    name: data for name, data in roc_store.items()
    if name in ["XGBoost", "SVM", "LogReg"]
}

plot_combined_roc(
    filtered_roc_store,
    title="Comparative ROC Curves (XGBoost, SVM, LogReg)",
    filename="comparative_roc_xgb_svm_logreg.png"
)

