# -*- coding: utf-8 -*-
"""EHR_featureEngineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYW5GBmZnqtHWYr2Pa7-n7GPSuh-K9km

# Data Pre-processing, ICD Conversion & Feature Engineering
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install icd-mappings

import pandas as pd
import numpy as np
import re
import ast
import json

import matplotlib.pyplot as plt
import seaborn as sns

"""# Dataset Merging & Rearranging"""

df_general = pd.read_csv('/content/drive/MyDrive/EHR/patients_table.csv')
df_general = df_general.drop(columns=['Unnamed: 0'])
df_general.head()

df_admit = pd.read_csv('/content/drive/MyDrive/EHR/patient_admissions.csv')
df_admit = df_admit.drop(columns=['Unnamed: 0'])
df_admit.head()

df_disease = pd.read_csv('/content/drive/MyDrive/EHR/disease_diagnosis_code.csv')
df_disease = df_disease.drop(columns=['Unnamed: 0'])
df_disease.head()

df_merged_data = pd.merge(df_general, df_admit, on='subject_id', how='inner')
df_merged_data.head()

df_final_merged = pd.merge(df_merged_data, df_disease, on=['subject_id', 'hadm_id'], how='inner')
df_final_merged.head()

# Rearranging the columns
# storing all column names from 'df_final_merged' dataframe as a list in 'cols' variable
cols = df_final_merged.columns.tolist()
hadm_id_col = 'hadm_id'
subject_id_idx = cols.index('subject_id') # finding the current index (or position of `'subject_id'`)

# Remove hadm_id from its current position
if hadm_id_col in cols:
    cols.remove(hadm_id_col)

# Insert hadm_id after subject_id
cols.insert(subject_id_idx + 1, hadm_id_col)

# Reassigning the dataframe with reordered columns according to new 'cols' list
df_final_merged = df_final_merged[cols]
df_final_merged.head()

df_final_merged

df_icd9_only = df_final_merged[df_final_merged['icd_version'] == 9]
df_icd9_only.head()

"""# ICD Conversion (ICD-9 -> ICD-10)"""

from icdmappings import Mapper

mapper = Mapper()

"""### Normalizing ICD Codes"""

# Defining function to clean the codes (if needed)
def normalize_dx(code):
    """Standardize diagnosis codes for mapping: uppercase, remove dots/spaces."""
    if pd.isna(code):
        return None
    s = str(code).strip().upper()
    s = s.replace('.', '')  # icdmappings works fine without dots
    s = re.sub(r'\s+', '', s)
    return s if s else None

# Defining function to shorten icd10 codes to a 3-character level
def icd10_to_3char(icd10):
    """
    Reduce ICD-10 to 3-character category (letter + 2 digits).
    Example: F0280 -> F02
    """
    if icd10 is None or (isinstance(icd10, float) and np.isnan(icd10)):
        return None
    s = str(icd10).strip().upper().replace('.', '')
    # Standard ICD-10 category pattern: 1 letter + 2 digits
    # an uppercase letter followed by two digits at the very beginning of the string
    m = re.match(r'^([A-Z]\d{2})', s)
    return m.group(1) if m else None

CODE_COL = "icd_code"
VER_COL  = "icd_version"

df = df_final_merged.copy() # Making a copy of the merged dataframe

df["dx_norm"] = df[CODE_COL].apply(normalize_dx) # creating a new column ("dx_norm") by applying the normalize_dx function to each value in "icd_code" stored in "CODE_VAL" variable to clean and standardize the codes

if VER_COL in df.columns:
    is_icd9  = df[VER_COL].astype(str).eq("9")
    # creating a Boolean Series by converting the column to string type and checking where its value is exactly "9"
    is_icd10 = df[VER_COL].astype(str).eq("10")
else:
    # Heuristic: ICD-10 often starts with a letter; ICD-9 usually begins with a digit
    is_icd10 = df["dx_norm"].fillna("").str.match(r"^[A-Z]")
    is_icd9  = df["dx_norm"].fillna("").str.match(r"^\d")

    # inside the else block, if there's no icd_version column, this line tries to identify ICD-10 codes. It assumes that ICD-10 codes typically start with a letter. It takes the "dx_norm" column, fills any NaN values with an empty string, and then checks if the normalized code starts with an uppercase letter using a regular expression ^[A-Z].

    # Also within the else block, this line attempts to identify ICD-9 codes. It assumes that ICD-9 codes usually start with a digit. It checks if the normalized code starts with a digit using the regular expression ^\d.

# New column with initial values for all rows set to none
df["icd10_full"] = None

# Keeping existing ICD-10 codes
df.loc[is_icd10, "icd10_full"] = df.loc[is_icd10, "dx_norm"]
# for the rows identified by Boolean Series (is_icd10), the "icd10_full" column is filled by values from "dx_norm" column

# Map ICD-9 codes to ICD-10 (vectorized)
icd9_list = df.loc[is_icd9, "dx_norm"].tolist()
mapped_icd10 = mapper.map(icd9_list, source="icd9", target="icd10")  # returns list w/ None for invalids

# Assigning the mapped list back to "icd10_full" column (in icd9 rows)
df.loc[is_icd9, "icd10_full"] = mapped_icd10

df["icd10_3char"] = df["icd10_full"].apply(icd10_to_3char)

# (Optional) quick QA
print("Total rows:", len(df))
print("ICD-9 mapped:", df.loc[is_icd9, "icd10_full"].notna().mean())
print("3-char non-null:", df["icd10_3char"].notna().mean())

# View unmapped ICD-9 codes
unmapped = df.loc[is_icd9 & df["icd10_full"].isna(), CODE_COL].value_counts().head(20)
print(unmapped)

df

empty_list_count = df['icd10_full'].apply(lambda x: isinstance(x, list) and len(x) == 0).sum()

if empty_list_count > 0:
    print(f"There are {empty_list_count} values in 'icd10_full' that are empty lists ([])")
else:
    print("No empty lists ([]) found in the 'icd10_full' column.")

"""### Checking Null Values"""

print(f"Null values in 'icd10_full': {df['icd10_full'].isnull().sum()}")
print(f"Null values in 'icd10_3char': {df['icd10_3char'].isnull().sum()}")

# Dropping the rows with NaN in the 'icd10_full' column
df = df.dropna(subset=['icd10_full']).copy()

"""Let's break down the code: `df = df.dropna(subset=['icd10_full']).copy()`

- `df.dropna()`: This is a pandas DataFrame method used to remove rows or columns that contain missing values (represented as `NaN` or `None`).
- `subset=['icd10_full']`: This argument tells `dropna()` to only consider the `'icd10_full'` column when looking for missing values. If a row has a missing value *in this specific column*, that row will be dropped. Rows with missing values in other columns will be retained, as long as `icd10_full` is not missing.
- `.copy()`: After dropping the rows, `.copy()` is called. This creates a completely new DataFrame object. This is a best practice in pandas to avoid potential `SettingWithCopyWarning` and ensures that `df` is an independent DataFrame, preventing unintended modifications to views or slices of other DataFrames.
- `df = ...`: Finally, the resulting DataFrame (after dropping rows and creating a copy) is assigned back to the variable `df`, effectively updating the DataFrame `df` in your notebook.
"""

print(f"New number of rows after removing nulls in 'icd10_full': {len(df)}")
print(f"Null values in 'icd10_full' after dropping: {df['icd10_full'].isnull().sum()}")
print(f"Null values in 'icd10_3char' after dropping: {df['icd10_3char'].isnull().sum()}")

df

df.to_csv('/content/drive/MyDrive/EHR/icd9_converted.csv', index=False)

"""### CCSR Mapping

"""

# ---------------------------
# 1) Loading CCSR mapping file (codes + categories + descriptions)
# ---------------------------
ccsr = pd.read_csv("/content/drive/MyDrive/EHR/DXCCSR_v2026-1.csv", dtype=str, keep_default_na=False)

# Cleaning column names: removing leading/trailing apostrophes/spaces
ccsr.columns = [re.sub(r"^'+|'+$", "", c.strip()) for c in ccsr.columns]

# Identifying the parallel category and description columns (1..6)
cat_cols  = [c for c in ccsr.columns if re.fullmatch(r"CCSR CATEGORY [1-6]", c)]
desc_cols = [f"{c} DESCRIPTION" for c in cat_cols]

# Cleaning ICD-10 codes (no decimals, uppercase) for join consistency
ccsr["icd10"] = (
    ccsr["ICD-10-CM CODE"]
    .str.strip()
    .str.strip("'")
    .str.replace(".", "", regex=False)
    .str.upper()
)

# Cleaning category & description columns
for c in cat_cols + desc_cols:
    ccsr[c] = ccsr[c].astype(str).str.strip().str.strip("'")

# (A) Building LONG mapping for categories only (icd10 -> ccsr_category)
ccsr_long_cat = (
    ccsr[["icd10"] + cat_cols]
    .melt(id_vars="icd10", value_vars=cat_cols, value_name="ccsr_category")
)
ccsr_long_cat = ccsr_long_cat[~ccsr_long_cat["ccsr_category"].isin(["", " ", None, np.nan])]
ccsr_long_cat = ccsr_long_cat.drop(columns="variable").drop_duplicates()

# (B) Building LONG mapping for (icd10 -> ccsr_category + ccsr_description) by aligning parallel columns
ccsr_cat_long = (
    ccsr[["icd10"] + cat_cols]
    .melt(id_vars="icd10", value_vars=cat_cols, var_name="cat_var", value_name="ccsr_category")
)
ccsr_desc_long = (
    ccsr[["icd10"] + desc_cols]
    .melt(id_vars="icd10", value_vars=desc_cols, var_name="desc_var", value_name="ccsr_description")
)

# Aligning by index (melt preserves order)
assert len(ccsr_cat_long) == len(ccsr_desc_long)
ccsr_long_full = pd.concat([ccsr_cat_long, ccsr_desc_long.drop(columns=['icd10'])], axis=1)
ccsr_long_full = (
    ccsr_long_full[~ccsr_long_full["ccsr_category"].isin(["", " ", None, np.nan])]
    .drop(columns=["cat_var", "desc_var"])
    .drop_duplicates(subset=["icd10", "ccsr_category", "ccsr_description"])
)

# ---------------------------
# 2) Loading harmonized diagnoses and preparing ICD-10 codes
# ---------------------------
# Using the 'df' DataFrame created in previous steps.
dx = df.copy()

# 'icd10_full' does NOT contain lists (no []), so no need for create exploding. Each row already corresponds to a single ICD-10 code.

dx_long = dx.copy()

# Standardizing ICD-10 codes (no decimals, uppercase) for join consistency
dx_long["icd10"] = (
    dx_long["icd10_full"]
    .astype(str)
    .str.strip()
    .str.replace(".", "", regex=False)
    .str.upper()
)

# Replacing invalid placeholders with NA
dx_long.loc[dx_long["icd10"].isin(["", "NAN", "NONE"]), "icd10"] = pd.NA

# ---------------------------
# 3) Merge ICD-10 -> CCSR category + description
# ---------------------------
dx_ccsr_long = dx_long.merge(ccsr_long_full, on="icd10", how="left")

# ---------------------------
# 4) Aggregate back to one row per (subject_id, hadm_id, seq_num)
# ---------------------------
key_cols = ["subject_id", "hadm_id", "seq_num"]

# Build code list
ccsr_agg_codes = (
    dx_ccsr_long.dropna(subset=["ccsr_category"])
    .groupby(key_cols)["ccsr_category"]
    .apply(lambda s: sorted(set(s)))
    .reset_index(name="ccsr_list_sorted")  # Renamed to avoid confusion
)

# Build aligned description list (category -> description; keep one per category; sort by code)
def collect_desc(rows: pd.DataFrame):
    # rows has columns: ccsr_category, ccsr_description
    pairs = {(cat, desc) for cat, desc in zip(rows["ccsr_category"], rows["ccsr_description"]) if pd.notna(cat)}
    cat_to_desc = {}
    for cat, desc in pairs:
        if cat not in cat_to_desc and isinstance(desc, str) and desc.strip() != "":
            cat_to_desc[cat] = desc.strip()
    cats_sorted = sorted(cat_to_desc.keys())
    desc_sorted = [cat_to_desc[c] for c in cats_sorted]
    return pd.Series({"ccsr_list_sorted": cats_sorted, "ccsr_description": desc_sorted})

ccsr_agg_desc = (
    dx_ccsr_long.dropna(subset=["ccsr_category"])
    .groupby(key_cols)
    .apply(collect_desc, include_groups=False)
    .reset_index()
)

# Merge lists back to harmonized dataframe
dx_with_ccsr = dx.merge(ccsr_agg_desc, on=key_cols, how="left")

# Removed the creation of 'ccsr_list' as 'ccsr_list_sorted' is sufficient
# For backward compatibility: ensure list-typed outputs
dx_with_ccsr["ccsr_description"] = dx_with_ccsr["ccsr_description"].apply(lambda x: x if isinstance(x, list) else [])



dx_with_ccsr

rows_with_multiple_ccsr = dx_with_ccsr[dx_with_ccsr['ccsr_list_sorted'].apply(lambda x: isinstance(x, list) and len(x) > 1)]
print(f"Number of rows where 'ccsr_list_sorted' has more than one element: {len(rows_with_multiple_ccsr)}")
rows_with_multiple_ccsr

dx_with_ccsr.to_csv("/content/drive/MyDrive/EHR/dx_with_ccsr_desc.csv", index=False)

"""# Feature Engineering"""

# === Input (final merged file) ===
infile = "/content/drive/MyDrive/EHR/dx_with_ccsr_desc.csv"
df = pd.read_csv(infile, dtype=str, keep_default_na=False)

# --- Treating blank-like strings as missing, without dropping/overwriting columns ---
BLANKS = {"", " ", "NA", "N/A", "None", "NONE", "NaN", "nan"}
def to_na(s: pd.Series) -> pd.Series:
    return s.apply(lambda v: (np.nan if (isinstance(v, str) and v.strip() in BLANKS) else v))

for col in ["gender", "race", "admission_type", "hospital_expire_flag", "anchor_age", "anchor_year"]:
    if col in df.columns:
        df[col] = to_na(df[col])

# --- Gender: normalize to {M,F,NaN} in the SAME column ---
if "gender" in df.columns:
    g = df["gender"].str.upper().str.strip()
    df["gender"] = g.where(g.isin(["M","F"]))  # any other value -> NaN

# --- Numeric encoders for race & admission_type (add code columns; keep originals) ---
label_maps = {}
for col in ["race", "admission_type", "gender"]:
    if col in df.columns:
        ser = df[col].astype(str).str.strip()
        ser = ser.where(~ser.isin(BLANKS))          # keep NaN as missing
        cat = pd.Categorical(ser)                   # categories inferred from this file
        df[col + "_code"] = cat.codes.astype("int32")  # -1 represents missing
        label_maps[col] = {cat.categories[i]: int(i) for i in range(len(cat.categories))}

# --- Target: coerce to {0,1}; keep the column ---
if "hospital_expire_flag" in df.columns:
    df["hospital_expire_flag"] = (
        pd.to_numeric(df["hospital_expire_flag"], errors="coerce")
          .fillna(0).clip(0,1).astype(int)
    )

# --- Parse timestamps non-destructively ---
for tcol in ["admittime", "dischtime", "deathtime"]:
    if tcol in df.columns:
        df[f"{tcol}_dt"] = pd.to_datetime(df[tcol], errors="coerce")

# --- Length of stay (LOS) features (added) ---
if {"admittime_dt","dischtime_dt"}.issubset(df.columns):
    disch_proxy = df["dischtime_dt"].copy()
    if "deathtime_dt" in df.columns:
        disch_proxy = disch_proxy.fillna(df["deathtime_dt"])
    los_hours = (disch_proxy - df["admittime_dt"]).dt.total_seconds() / 3600.0
    df["los_hours"] = np.where(np.isfinite(los_hours), np.maximum(0, los_hours), np.nan)
    df["los_days"]  = df["los_hours"] / 24.0

# --- Calendar/time features (added) ---
if "admittime_dt" in df.columns:
    df["adm_year"]    = df["admittime_dt"].dt.year
    df["adm_month"]   = df["admittime_dt"].dt.month
    df["adm_day"]     = df["admittime_dt"].dt.day
    df["adm_hour"]    = df["admittime_dt"].dt.hour
    df["adm_weekday"] = df["admittime_dt"].dt.weekday  # 0=Mon..6=Sun
    df["adm_weekend"] = df["adm_weekday"].isin([5,6]).astype(int)

# --- Age at admission (added) from anchor_age/anchor_year and admission year ---
if {"anchor_age","anchor_year"}.issubset(df.columns) and "adm_year" in df.columns:
    aa = pd.to_numeric(df["anchor_age"], errors="coerce")
    ay = pd.to_numeric(df["anchor_year"], errors="coerce")
    df["age_at_admit"] = aa + (df["adm_year"] - ay)
    df.loc[(df["age_at_admit"] < 0) | (df["age_at_admit"] > 120), "age_at_admit"] = np.nan

# --- Optional breadth feature from CCSR list (added) ---
if "ccsr_list_sorted" in df.columns:
    def count_list_like(x):
        if isinstance(x, list): return len(x)
        if isinstance(x, str) and x.startswith("[") and x.endswith("]"):
            try:
                v = ast.literal_eval(x)
                return len(v) if isinstance(v, list) else 0
            except Exception:
                return 0
        return 0
    df["n_ccsr"] = df["ccsr_list_sorted"].apply(count_list_like)

# --- Save the full dataframe with ALL original columns + features/encodings ---
out_all = "/content/drive/MyDrive/EHR/dx_encoded_feats.csv"
df.to_csv(out_all, index=False)

# Save label maps for reproducibility of numeric encoders
with open("/content/drive/MyDrive/EHR/categorical_label_maps.json","w") as f:
    json.dump(label_maps, f, indent=2)

print("Saved", out_all, "with shape", df.shape)
print("Saved categorical_label_maps.json with keys:", list(label_maps.keys()))

df

young_patients = df[df['age_at_admit'] < 18]

print(f"Number of patients below 18 years old: {len(young_patients)}")
print("Patients below 18 years old:")
young_patients

"""# Data Exploration"""

df_viz = pd.read_csv('/content/drive/MyDrive/EHR/dx_encoded_feats.csv')
df_viz.head()

plt.figure(figsize=(6, 4))
sns.countplot(data=df_viz, x='gender', hue='gender', palette='viridis', legend=False)
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(data=df_viz, x='age_at_admit', bins=20, kde=True, color='#9883E5')
plt.title('Distribution of Age at Admission')
plt.xlabel('Age at Admission')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(data=df_viz, x='admission_type', hue='admission_type', palette='viridis', legend=False)
plt.title('Distribution of Admission Type')
plt.xlabel('Admission Type')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(data=df_viz, x='los_days', bins=30, kde=True,
             color=sns.color_palette("muted")[0])
plt.title('Distribution of Length of Stay (Days)')
plt.xlabel('Length of Stay (Days)')
plt.ylabel('Count')

# --- Added: annotate x-value beside the tallest bar (no other changes) ---
ax = plt.gca()
patches = ax.patches
if patches:  # ensure there are bars
    # Find tallest bar
    heights = [p.get_height() for p in patches]
    idx_max = heights.index(max(heights))
    p_max = patches[idx_max]

    # Bin center (x-axis value of the highest peak)
    x_center = p_max.get_x() + p_max.get_width() / 2.0

    # Place label on the side (right side) of the tallest bar, vertically centered
    ax.text(
        p_max.get_x() + p_max.get_width() * 1.02,   # a bit to the right of the bar
        p_max.get_height() / 2.0,                   # vertical middle of the bar
        f"x = {x_center:.2f}",
        ha='left', va='center', color='black'
    )
# --- End added ---

plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(data=df_viz, x='los_days', bins=30, kde=True)
plt.title('Distribution of Length of Stay (Days)')
plt.xlabel('Length of Stay (Days)')
plt.ylabel('Count')
plt.show()

from collections import Counter

# Flatten the list of CCSR categories
all_ccsr_categories = []
for ccsr_list_str in df_viz['ccsr_list_sorted']:
    try:
        # Safely evaluate the string as a Python literal (list)
        ccsr_list = ast.literal_eval(ccsr_list_str)
        if isinstance(ccsr_list, list):
            all_ccsr_categories.extend(ccsr_list)
    except (ValueError, SyntaxError):
        # Handle cases where the string is not a valid list literal
        pass

# Count the frequency of each category
ccsr_counts = Counter(all_ccsr_categories)

# Get the top 10 most frequent categories
top_10_ccsr = pd.DataFrame(ccsr_counts.most_common(10), columns=['CCSR_Category', 'Count'])

plt.figure(figsize=(12, 6))
sns.barplot(data=top_10_ccsr, x='CCSR_Category', y='Count', hue='CCSR_Category', palette='viridis', legend=False)
plt.title('Top 10 Most Frequent CCSR Categories')
plt.xlabel('CCSR Category')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()



"""## Prepare mortality data for plotting

### Subtask:
Calculate the counts and percentages for 'hospital_expire_flag' and map the 0/1 values to 'Alive'/'Dead' labels.

"""

# Group the DataFrame by 'subject_id' and get the maximum 'hospital_expire_flag' for each patient.
# This ensures that if a patient had multiple admissions and expired in at least one, their status is '1' (Dead).
# .reset_index() converts the grouped result back into a DataFrame.
df_patient_mortality = df.groupby('subject_id')['hospital_expire_flag'].max().reset_index()
# Print the first few rows of the resulting DataFrame to inspect it.
print(df_patient_mortality.head())
# Print the total number of unique patients found.
print(f"Number of unique patients: {len(df_patient_mortality)}")




# Calculate the counts of 'Alive' (0) and 'Dead' (1) patients based on the unique patient mortality data.
mortality_counts = df_patient_mortality['hospital_expire_flag'].value_counts().reset_index()
# Rename the columns for clarity: 'hospital_expire_flag' (which now holds 0 or 1) and 'Count'.
mortality_counts.columns = ['hospital_expire_flag', 'Count']

# Calculate the percentage of 'Alive' and 'Dead' patients.
mortality_counts['Percentage'] = (mortality_counts['Count'] / mortality_counts['Count'].sum()) * 100

# Map the numerical 'hospital_expire_flag' (0 and 1) to descriptive labels 'Alive' and 'Dead' for better readability.
mortality_counts['hospital_expire_flag'] = mortality_counts['hospital_expire_flag'].map({0: 'Alive', 1: 'Dead'})

# Print a header for the output.
print("Mortality Counts and Percentages:")
# Print the final DataFrame containing the mortality counts and percentages.
print(mortality_counts)

"""**Reasoning**:
The previous step successfully prepared the mortality data. The next logical step, as per the task description, is to create a bar plot to visualize the distribution of 'Alive' and 'Dead' patients, displaying percentages on top of each bar.


"""

# Create a new figure with a specified size for the plot.
plt.figure(figsize=(7, 5))
# Create a bar plot using seaborn, displaying 'hospital_expire_flag' on the x-axis and 'Count' on the y-axis.
# 'hue' is set to 'hospital_expire_flag' for different bar colors based on status, 'palette' for color scheme.
# 'legend=False' hides the legend as the x-axis labels are self-explanatory.
sns.barplot(x='hospital_expire_flag', y='Count', hue='hospital_expire_flag', data=mortality_counts, palette= ['#0D3B66','#EF6461'], legend=False)

# Set the title of the plot.
plt.title('Distribution of Hospital Mortality Status')
# Set the label for the x-axis.
plt.xlabel('Mortality Status')
# Set the label for the y-axis.
plt.ylabel('Number of Patients')

# Add percentage labels on top of the bars for better readability.
# Iterate through each row of the 'mortality_counts' DataFrame.
for index, row in mortality_counts.iterrows():
    # Use plt.text() to add text annotations. 'index' specifies the x-coordinate (bar position).
    # 'row['Count']' specifies the y-coordinate (top of the bar).
    # The text is formatted to display the percentage with two decimal places.
    # 'color', 'ha' (horizontal alignment), and 'va' (vertical alignment) are set for aesthetics.
    plt.text(index, row['Count'], f"{row['Percentage']:.2f}%", color='black', ha="center", va='bottom')

# Display the plot.
plt.show()

"""## Summary:

### Data Analysis Key Findings

*   The majority of patients in the dataset were discharged alive, with 131,575 patients, representing approximately 95.79% of the total.
*   A smaller proportion of patients expired in the hospital, with 5,786 patients, accounting for approximately 4.21% of the total.
*   The 'hospital_expire_flag' values of 0 and 1 were successfully mapped to 'Alive' and 'Dead' labels, respectively, facilitating clearer interpretation.
*   The distribution of hospital mortality status was visualized using a bar plot, clearly showing the disproportionate number of 'Alive' versus 'Dead' patients.

### Insights or Next Steps

*   The low hospital mortality rate suggests that the patient population, on average, has a high survival rate during hospitalization.
*   Future analysis could focus on identifying factors or patient characteristics associated with the 4.21% mortality rate to understand potential risks or areas for intervention.

"""

plt.figure(figsize=(16, 7))
ax = sns.countplot(data=df_viz, x='race', hue='race', palette='viridis', legend=False)
plt.title('Distribution of Race')
plt.xlabel('Race')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')

# Calculate percentages
total = len(df_viz['race'].dropna()) # Exclude NaN values for percentage calculation
for p in ax.patches:
    percentage = '{:.2f}%'.format(100 * p.get_height()/total)
    x = p.get_x() + p.get_width() / 2
    y = p.get_height()
    ax.annotate(percentage, (x, y), ha='center', va='bottom')

plt.tight_layout()
plt.savefig('race_distribution.png', dpi=500)
plt.show()